name: deploy

on:
  push:
    branches:
      - main
    paths:
      - "**.js"
      - "**.json"
      - "**.vue"
      - "**.css"
      - "!docs/**"

jobs:
  auto-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.1
      - run: npm ci
      - run: npm run build:docs
      - uses: stefanzweifel/git-auto-commit-action@v4.4.1
        with:
          commit_message: "chore: auto-deployment at ${{ steps.date.outputs.date }}"
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
